// Code generated by boompaw from path.bp. DO NOT EDIT.

package setaypath

import (
	"errors"
	"fmt"
	"strings"
)

var _ = fmt.Errorf
var _ = strings.HasPrefix


// Safety constants.
const (
	MaxParseDepth  = 2000
	MaxRepeatCount = 1_000_000
	MaxMemoEntries = 1_000_000
)

// Safety errors.
var (
	ErrDepthLimitExceeded  = errors.New("parse depth exceeded limit")
	ErrRepeatLimitExceeded = errors.New("repeat count exceeded limit")
	ErrMemoLimitExceeded   = errors.New("memo table exceeded limit")
)

// Position is a character position in source code (0-based, rune unit).
type Position int

// Length is the length of a node (rune unit).
type Length int

// LineNum is a line number in source code (1-based).
type LineNum int

// Authority holds the position information of a node in source code.
type Authority struct {
	SourceFilename string
	StartedAt      Position
	Length         Length
	StartedLineNum LineNum
	Surface        string
}

// ParseNode is the common interface for all parse result nodes.
type ParseNode interface {
	GetAuthority() *Authority
}

// StringFromSource holds a string and its position information from a leaf node.
type StringFromSource struct {
	Authority *Authority
	Surface   string
}

// GetAuthority implements ParseNode for StringFromSource.
func (s StringFromSource) GetAuthority() *Authority { return s.Authority }

type memoEntry struct {
	node ParseNode
	end  int
	err  error
}

// PackratParser is the packrat parser implementation.
type PackratParser struct {
	input       []rune
	memo        map[string]map[int]*memoEntry
	depth       int
	memoCount   int
	furthestPos int    // furthest position reached during parsing
	furthestMsg string // error message at the furthest position
	lineOffsets []int  // positions of each '\n' in input (pre-computed)
}

// NewPackratParser creates a new parser.
func NewPackratParser(input string) *PackratParser {
	runes := []rune(input)
	// Pre-compute line offset table: record position of every '\n'.
	var offsets []int
	for i, r := range runes {
		if r == '\n' {
			offsets = append(offsets, i)
		}
	}
	return &PackratParser{
		input:       runes,
		memo:        make(map[string]map[int]*memoEntry),
		furthestPos: -1,
		lineOffsets: offsets,
	}
}

func (p *PackratParser) enterRule() error {
	p.depth++
	if p.depth > MaxParseDepth {
		return fmt.Errorf("%w: depth=%d", ErrDepthLimitExceeded, p.depth)
	}
	return nil
}

func (p *PackratParser) leaveRule() {
	p.depth--
}

func (p *PackratParser) memoize(rule string, pos int, node ParseNode, end int, err error) {
	if p.memo[rule] == nil {
		p.memo[rule] = make(map[int]*memoEntry)
	}
	if _, exists := p.memo[rule][pos]; !exists {
		p.memoCount++
	}
	p.memo[rule][pos] = &memoEntry{node: node, end: end, err: err}
	if err != nil {
		p.trackFailure(end, err)
	}
}

func (p *PackratParser) trackFailure(pos int, err error) {
	if pos > p.furthestPos {
		p.furthestPos = pos
		p.furthestMsg = err.Error()
	}
}

func (p *PackratParser) getMemo(rule string, pos int) (*memoEntry, bool) {
	if m, ok := p.memo[rule]; ok {
		if e, ok := m[pos]; ok {
			return e, true
		}
	}
	return nil, false
}

func (p *PackratParser) lineAt(pos int) LineNum {
	// Binary search: find how many '\n' characters appear before pos.
	lo, hi := 0, len(p.lineOffsets)
	for lo < hi {
		mid := lo + (hi-lo)/2
		if p.lineOffsets[mid] < pos {
			lo = mid + 1
		} else {
			hi = mid
		}
	}
	return LineNum(lo + 1)
}

func (p *PackratParser) makeAuthority(start, end int) *Authority {
	return &Authority{
		StartedAt:      Position(start),
		Length:         Length(end - start),
		StartedLineNum: p.lineAt(start),
		Surface:        string(p.input[start:end]),
	}
}

func (p *PackratParser) makeStringFromSource(start, end int) StringFromSource {
	return StringFromSource{
		Authority: p.makeAuthority(start, end),
		Surface:   string(p.input[start:end]),
	}
}

func (p *PackratParser) extractIdentText(startPos, pos int) string {
	end := pos
	start := end
	for start > startPos {
		ch := p.input[start-1]
		if (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') ||
			(ch >= '0' && ch <= '9') || ch == '_' || ch == '-' {
			start--
		} else {
			break
		}
	}
	return string(p.input[start:end])
}

// DefSetayPath is the parse result of the SetayPath rule.
type DefSetayPath struct {
	Authority *Authority
	AnonymousField1 StringFromSource
	First *DefSetayPathSegment
	Rest []*DefSetayPathSegmentSep
}

func (n *DefSetayPath) GetAuthority() *Authority { return n.Authority }

// DefSetayPathSegmentSep is the parse result of the SetayPathSegmentSep rule.
type DefSetayPathSegmentSep struct {
	Authority *Authority
	AnonymousField1 StringFromSource
	Segment *DefSetayPathSegment
}

func (n *DefSetayPathSegmentSep) GetAuthority() *Authority { return n.Authority }

// DefSetayPathSegment is the parse result of the SetayPathSegment rule.
type DefSetayPathSegment struct {
	Authority *Authority
	AnonymousField1 ParseNode
}

func (n *DefSetayPathSegment) GetAuthority() *Authority { return n.Authority }

// DefSetayPathIndex is the parse result of the SetayPathIndex rule.
type DefSetayPathIndex struct {
	Authority *Authority
	Sign []*DefSetayPathMinus
	Digits []*DefSetayPathDigit
}

func (n *DefSetayPathIndex) GetAuthority() *Authority { return n.Authority }

// DefSetayPathMinus is the parse result of the SetayPathMinus rule.
type DefSetayPathMinus struct {
	Authority *Authority
	AnonymousField1 StringFromSource
}

func (n *DefSetayPathMinus) GetAuthority() *Authority { return n.Authority }

// DefSetayPathDigit is the parse result of the SetayPathDigit rule.
type DefSetayPathDigit struct {
	Authority *Authority
	AnonymousField1 StringFromSource
}

func (n *DefSetayPathDigit) GetAuthority() *Authority { return n.Authority }

// DefSetayPathUnquotedKey is the parse result of the SetayPathUnquotedKey rule.
type DefSetayPathUnquotedKey struct {
	Authority *Authority
	FirstCh *DefSetayPathKeyLead
	Trailing []*DefSetayPathKeyTrailing
}

func (n *DefSetayPathUnquotedKey) GetAuthority() *Authority { return n.Authority }

// DefSetayPathKeyTrailing is the parse result of the SetayPathKeyTrailing rule.
type DefSetayPathKeyTrailing struct {
	Authority *Authority
	MidChars []*DefSetayPathKeyMid
	LastCh *DefSetayPathKeyLast
}

func (n *DefSetayPathKeyTrailing) GetAuthority() *Authority { return n.Authority }

// DefSetayPathKeyLead is the parse result of the SetayPathKeyLead rule.
type DefSetayPathKeyLead struct {
	Authority *Authority
	AnonymousField1 ParseNode
}

func (n *DefSetayPathKeyLead) GetAuthority() *Authority { return n.Authority }

// DefSetayPathKeyMid is the parse result of the SetayPathKeyMid rule.
type DefSetayPathKeyMid struct {
	Authority *Authority
	AnonymousField1 ParseNode
}

func (n *DefSetayPathKeyMid) GetAuthority() *Authority { return n.Authority }

// DefSetayPathKeyLast is the parse result of the SetayPathKeyLast rule.
type DefSetayPathKeyLast struct {
	Authority *Authority
	AnonymousField1 ParseNode
}

func (n *DefSetayPathKeyLast) GetAuthority() *Authority { return n.Authority }

// DefSetayPathQuotedKey is the parse result of the SetayPathQuotedKey rule.
type DefSetayPathQuotedKey struct {
	Authority *Authority
	AnonymousField1 ParseNode
}

func (n *DefSetayPathQuotedKey) GetAuthority() *Authority { return n.Authority }

// DefSetayPathDqKey is the parse result of the SetayPathDqKey rule.
type DefSetayPathDqKey struct {
	Authority *Authority
	AnonymousField1 StringFromSource
	Content []*DefSetayPathDqContent
	AnonymousField2 StringFromSource
}

func (n *DefSetayPathDqKey) GetAuthority() *Authority { return n.Authority }

// DefSetayPathDqContent is the parse result of the SetayPathDqContent rule.
type DefSetayPathDqContent struct {
	Authority *Authority
	AnonymousField1 ParseNode
}

func (n *DefSetayPathDqContent) GetAuthority() *Authority { return n.Authority }

// DefSetayPathDqNormal is the parse result of the SetayPathDqNormal rule.
type DefSetayPathDqNormal struct {
	Authority *Authority
	AnonymousField1 StringFromSource
}

func (n *DefSetayPathDqNormal) GetAuthority() *Authority { return n.Authority }

// DefSetayPathSqKey is the parse result of the SetayPathSqKey rule.
type DefSetayPathSqKey struct {
	Authority *Authority
	AnonymousField1 StringFromSource
	Content []*DefSetayPathSqContent
	AnonymousField2 StringFromSource
}

func (n *DefSetayPathSqKey) GetAuthority() *Authority { return n.Authority }

// DefSetayPathSqContent is the parse result of the SetayPathSqContent rule.
type DefSetayPathSqContent struct {
	Authority *Authority
	AnonymousField1 ParseNode
}

func (n *DefSetayPathSqContent) GetAuthority() *Authority { return n.Authority }

// DefSetayPathSqNormal is the parse result of the SetayPathSqNormal rule.
type DefSetayPathSqNormal struct {
	Authority *Authority
	AnonymousField1 StringFromSource
}

func (n *DefSetayPathSqNormal) GetAuthority() *Authority { return n.Authority }

// DefSetayPathEscape is the parse result of the SetayPathEscape rule.
type DefSetayPathEscape struct {
	Authority *Authority
	AnonymousField1 StringFromSource
	Ch *DefSetayPathEscapeChar
}

func (n *DefSetayPathEscape) GetAuthority() *Authority { return n.Authority }

// DefSetayPathEscapeChar is the parse result of the SetayPathEscapeChar rule.
type DefSetayPathEscapeChar struct {
	Authority *Authority
	AnonymousField1 ParseNode
}

func (n *DefSetayPathEscapeChar) GetAuthority() *Authority { return n.Authority }

// DefSetayPathAsciiSymbol is the parse result of the SetayPathAsciiSymbol rule.
type DefSetayPathAsciiSymbol struct {
	Authority *Authority
	AnonymousField1 ParseNode
}

func (n *DefSetayPathAsciiSymbol) GetAuthority() *Authority { return n.Authority }

// DefSetayPathHexEscape is the parse result of the SetayPathHexEscape rule.
type DefSetayPathHexEscape struct {
	Authority *Authority
	AnonymousField1 StringFromSource
	AnonymousField2 *DefSetayPathHex07
	AnonymousField3 *DefSetayPathHexDigit
}

func (n *DefSetayPathHexEscape) GetAuthority() *Authority { return n.Authority }

// DefSetayPathHex07 is the parse result of the SetayPathHex07 rule.
type DefSetayPathHex07 struct {
	Authority *Authority
	AnonymousField1 StringFromSource
}

func (n *DefSetayPathHex07) GetAuthority() *Authority { return n.Authority }

// DefSetayPathUnicode4 is the parse result of the SetayPathUnicode4 rule.
type DefSetayPathUnicode4 struct {
	Authority *Authority
	AnonymousField1 StringFromSource
	AnonymousField2 *DefSetayPathHexDigit
	AnonymousField3 *DefSetayPathHexDigit
	AnonymousField4 *DefSetayPathHexDigit
	AnonymousField5 *DefSetayPathHexDigit
}

func (n *DefSetayPathUnicode4) GetAuthority() *Authority { return n.Authority }

// DefSetayPathUnicode8 is the parse result of the SetayPathUnicode8 rule.
type DefSetayPathUnicode8 struct {
	Authority *Authority
	AnonymousField1 StringFromSource
	AnonymousField2 *DefSetayPathHexDigit
	AnonymousField3 *DefSetayPathHexDigit
	AnonymousField4 *DefSetayPathHexDigit
	AnonymousField5 *DefSetayPathHexDigit
	AnonymousField6 *DefSetayPathHexDigit
	AnonymousField7 *DefSetayPathHexDigit
	AnonymousField8 *DefSetayPathHexDigit
	AnonymousField9 *DefSetayPathHexDigit
}

func (n *DefSetayPathUnicode8) GetAuthority() *Authority { return n.Authority }

// DefSetayPathHexDigit is the parse result of the SetayPathHexDigit rule.
type DefSetayPathHexDigit struct {
	Authority *Authority
	AnonymousField1 ParseNode
}

func (n *DefSetayPathHexDigit) GetAuthority() *Authority { return n.Authority }

// Parse parses the input string and returns a SetayPath.
func Parse(input string) (*DefSetayPath, error) {
	p := NewPackratParser(input)
	node, end, err := p.parseSetayPath(0)
	if err != nil {
		if p.furthestPos > 0 {
			return nil, fmt.Errorf("Parse error at position %d (line %d): %s — near: %q", p.furthestPos, p.lineAt(p.furthestPos), p.furthestMsg, string(p.input[p.furthestPos:min(p.furthestPos+20, len(p.input))]))
		}
		return nil, err
	}
	if end < len(p.input) {
		if p.furthestPos > end {
			return nil, fmt.Errorf("Parse error at position %d (line %d): %s — near: %q", p.furthestPos, p.lineAt(p.furthestPos), p.furthestMsg, string(p.input[p.furthestPos:min(p.furthestPos+20, len(p.input))]))
		}
		return nil, fmt.Errorf("unexpected input at position %d (line %d): %q", end, p.lineAt(end), string(p.input[end:min(end+20, len(p.input))]))
	}
	return node, nil
}

func (p *PackratParser) parseSetayPath(pos int) (*DefSetayPath, int, error) {
	if m, ok := p.getMemo("SetayPath", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPath), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPath{}

	// Field: AnonymousField1 (Literal ":/")
	{
		expected := []rune(":/")
		if pos+len(expected) > len(p.input) {
			err := fmt.Errorf("line %d: expected %q, got EOF", p.lineAt(pos), ":/")
			p.memoize("SetayPath", startPos, nil, pos, err)
			return nil, pos, err
		}
		matched := true
		for i, r := range expected {
			if p.input[pos+i] != r { matched = false; break }
		}
		if !matched {
			err := fmt.Errorf("line %d: expected %q", p.lineAt(pos), ":/")
			p.memoize("SetayPath", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
		pos += len(expected)
	}
	// Field: First (Reference -> SetayPathSegment)
	{
		node, end, err := p.parseSetayPathSegment(pos)
		if err != nil {
			p.memoize("SetayPath", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.First = node
		pos = end
	}
	// Field: Rest (Repeat)
	{
		var repCount int
		for {
			repCount++
			if repCount > MaxRepeatCount { return nil, pos, ErrRepeatLimitExceeded }
			node, end, err := p.parseSetayPathSegmentSep(pos)
			if err != nil { break }
			if end == pos { break } // prevent zero-length match
			result.Rest = append(result.Rest, node)
			pos = end
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPath", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathSegmentSep(pos int) (*DefSetayPathSegmentSep, int, error) {
	if m, ok := p.getMemo("SetayPathSegmentSep", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathSegmentSep), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathSegmentSep{}

	// Field: AnonymousField1 (Literal ".")
	{
		expected := []rune(".")
		if pos+len(expected) > len(p.input) {
			err := fmt.Errorf("line %d: expected %q, got EOF", p.lineAt(pos), ".")
			p.memoize("SetayPathSegmentSep", startPos, nil, pos, err)
			return nil, pos, err
		}
		matched := true
		for i, r := range expected {
			if p.input[pos+i] != r { matched = false; break }
		}
		if !matched {
			err := fmt.Errorf("line %d: expected %q", p.lineAt(pos), ".")
			p.memoize("SetayPathSegmentSep", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
		pos += len(expected)
	}
	// Field: Segment (Reference -> SetayPathSegment)
	{
		node, end, err := p.parseSetayPathSegment(pos)
		if err != nil {
			p.memoize("SetayPathSegmentSep", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.Segment = node
		pos = end
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathSegmentSep", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathSegment(pos int) (*DefSetayPathSegment, int, error) {
	if m, ok := p.getMemo("SetayPathSegment", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathSegment), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathSegment{}

	// Field: AnonymousField1 (Choice)
	{
		var choiceMatched bool
		if !choiceMatched {
			node, end, err := p.parseSetayPathIndex(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			node, end, err := p.parseSetayPathUnquotedKey(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			node, end, err := p.parseSetayPathQuotedKey(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			err := fmt.Errorf("line %d: no choice matched for field AnonymousField1", p.lineAt(pos))
			p.memoize("SetayPathSegment", startPos, nil, pos, err)
			return nil, pos, err
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathSegment", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathIndex(pos int) (*DefSetayPathIndex, int, error) {
	if m, ok := p.getMemo("SetayPathIndex", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathIndex), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathIndex{}

	// Field: Sign (Repeat with backtracking)
	{
		var repPositions []int
		repPositions = append(repPositions, pos) // initial position
		var repCount int
		for {
			repCount++
			if repCount > MaxRepeatCount { return nil, pos, ErrRepeatLimitExceeded }
			node, end, err := p.parseSetayPathMinus(pos)
			if err != nil { break }
			result.Sign = append(result.Sign, node)
			pos = end
			repPositions = append(repPositions, pos)
			if len(result.Sign) >= 1 { break }
		}
		for {
			var seqErr error
			seqPos := pos
			if seqErr == nil {
				var repCount int
				for {
					repCount++
					if repCount > MaxRepeatCount { seqErr = ErrRepeatLimitExceeded; break }
					node, end, err := p.parseSetayPathDigit(seqPos)
					if err != nil { break }
					result.Digits = append(result.Digits, node)
					seqPos = end
				}
				if seqErr == nil && len(result.Digits) < 1 {
					seqErr = fmt.Errorf("line %d: expected at least 1 items for Digits", p.lineAt(seqPos))
				}
			}
			if seqErr == nil {
				pos = seqPos
				break // success
			}
			if len(result.Sign) == 0 {
				p.memoize("SetayPathIndex", startPos, nil, pos, seqErr)
				return nil, pos, seqErr
			}
			result.Sign = result.Sign[:len(result.Sign)-1]
			repPositions = repPositions[:len(repPositions)-1]
			pos = repPositions[len(repPositions)-1]
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathIndex", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathMinus(pos int) (*DefSetayPathMinus, int, error) {
	if m, ok := p.getMemo("SetayPathMinus", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathMinus), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathMinus{}

	// Field: AnonymousField1 (Literal "-")
	{
		expected := []rune("-")
		if pos+len(expected) > len(p.input) {
			err := fmt.Errorf("line %d: expected %q, got EOF", p.lineAt(pos), "-")
			p.memoize("SetayPathMinus", startPos, nil, pos, err)
			return nil, pos, err
		}
		matched := true
		for i, r := range expected {
			if p.input[pos+i] != r { matched = false; break }
		}
		if !matched {
			err := fmt.Errorf("line %d: expected %q", p.lineAt(pos), "-")
			p.memoize("SetayPathMinus", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
		pos += len(expected)
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathMinus", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathDigit(pos int) (*DefSetayPathDigit, int, error) {
	if m, ok := p.getMemo("SetayPathDigit", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathDigit), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathDigit{}

	// Field: AnonymousField1 (CharRange)
	{
		if pos >= len(p.input) {
			err := fmt.Errorf("line %d: expected char in range '0'..'9', got EOF", p.lineAt(pos))
			p.memoize("SetayPathDigit", startPos, nil, pos, err)
			return nil, pos, err
		}
		ch := p.input[pos]
		if ch < '0' || ch > '9' {
			err := fmt.Errorf("line %d: char %q not in range '0'..'9'", p.lineAt(pos), string(ch))
			p.memoize("SetayPathDigit", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
		pos++
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathDigit", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathUnquotedKey(pos int) (*DefSetayPathUnquotedKey, int, error) {
	if m, ok := p.getMemo("SetayPathUnquotedKey", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathUnquotedKey), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathUnquotedKey{}

	// Field: FirstCh (Reference -> SetayPathKeyLead)
	{
		node, end, err := p.parseSetayPathKeyLead(pos)
		if err != nil {
			p.memoize("SetayPathUnquotedKey", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.FirstCh = node
		pos = end
	}
	// Field: Trailing (Repeat)
	{
		var repCount int
		for {
			repCount++
			if repCount > MaxRepeatCount { return nil, pos, ErrRepeatLimitExceeded }
			node, end, err := p.parseSetayPathKeyTrailing(pos)
			if err != nil { break }
			if end == pos { break } // prevent zero-length match
			result.Trailing = append(result.Trailing, node)
			pos = end
			if len(result.Trailing) >= 1 { break }
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathUnquotedKey", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathKeyTrailing(pos int) (*DefSetayPathKeyTrailing, int, error) {
	if m, ok := p.getMemo("SetayPathKeyTrailing", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathKeyTrailing), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathKeyTrailing{}

	// Field: MidChars (Repeat with backtracking)
	{
		var repPositions []int
		repPositions = append(repPositions, pos) // initial position
		var repCount int
		for {
			repCount++
			if repCount > MaxRepeatCount { return nil, pos, ErrRepeatLimitExceeded }
			node, end, err := p.parseSetayPathKeyMid(pos)
			if err != nil { break }
			result.MidChars = append(result.MidChars, node)
			pos = end
			repPositions = append(repPositions, pos)
		}
		for {
			var seqErr error
			seqPos := pos
			if seqErr == nil {
				node, end, err := p.parseSetayPathKeyLast(seqPos)
				if err != nil { seqErr = err } else {
					result.LastCh = node
					seqPos = end
				}
			}
			if seqErr == nil {
				pos = seqPos
				break // success
			}
			if len(result.MidChars) == 0 {
				p.memoize("SetayPathKeyTrailing", startPos, nil, pos, seqErr)
				return nil, pos, seqErr
			}
			result.MidChars = result.MidChars[:len(result.MidChars)-1]
			repPositions = repPositions[:len(repPositions)-1]
			pos = repPositions[len(repPositions)-1]
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathKeyTrailing", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathKeyLead(pos int) (*DefSetayPathKeyLead, int, error) {
	if m, ok := p.getMemo("SetayPathKeyLead", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathKeyLead), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathKeyLead{}

	// Field: AnonymousField1 (Choice)
	{
		var choiceMatched bool
		if !choiceMatched {
			if pos < len(p.input) && p.input[pos] >= 'a' && p.input[pos] <= 'z' {
				result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
				pos++
				choiceMatched = true
			}
		}
		if !choiceMatched {
			if pos < len(p.input) && p.input[pos] >= 'A' && p.input[pos] <= 'Z' {
				result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
				pos++
				choiceMatched = true
			}
		}
		if !choiceMatched {
			expected := []rune("_")
			if pos+len(expected) <= len(p.input) {
				ok := true
				for i, r := range expected {
					if p.input[pos+i] != r { ok = false; break }
				}
				if ok {
					result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
					pos += len(expected)
					choiceMatched = true
				}
			}
		}
		if !choiceMatched {
			err := fmt.Errorf("line %d: no choice matched for field AnonymousField1", p.lineAt(pos))
			p.memoize("SetayPathKeyLead", startPos, nil, pos, err)
			return nil, pos, err
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathKeyLead", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathKeyMid(pos int) (*DefSetayPathKeyMid, int, error) {
	if m, ok := p.getMemo("SetayPathKeyMid", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathKeyMid), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathKeyMid{}

	// Field: AnonymousField1 (Choice)
	{
		var choiceMatched bool
		if !choiceMatched {
			if pos < len(p.input) && p.input[pos] >= 'a' && p.input[pos] <= 'z' {
				result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
				pos++
				choiceMatched = true
			}
		}
		if !choiceMatched {
			if pos < len(p.input) && p.input[pos] >= 'A' && p.input[pos] <= 'Z' {
				result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
				pos++
				choiceMatched = true
			}
		}
		if !choiceMatched {
			if pos < len(p.input) && p.input[pos] >= '0' && p.input[pos] <= '9' {
				result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
				pos++
				choiceMatched = true
			}
		}
		if !choiceMatched {
			expected := []rune("_")
			if pos+len(expected) <= len(p.input) {
				ok := true
				for i, r := range expected {
					if p.input[pos+i] != r { ok = false; break }
				}
				if ok {
					result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
					pos += len(expected)
					choiceMatched = true
				}
			}
		}
		if !choiceMatched {
			expected := []rune("-")
			if pos+len(expected) <= len(p.input) {
				ok := true
				for i, r := range expected {
					if p.input[pos+i] != r { ok = false; break }
				}
				if ok {
					result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
					pos += len(expected)
					choiceMatched = true
				}
			}
		}
		if !choiceMatched {
			err := fmt.Errorf("line %d: no choice matched for field AnonymousField1", p.lineAt(pos))
			p.memoize("SetayPathKeyMid", startPos, nil, pos, err)
			return nil, pos, err
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathKeyMid", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathKeyLast(pos int) (*DefSetayPathKeyLast, int, error) {
	if m, ok := p.getMemo("SetayPathKeyLast", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathKeyLast), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathKeyLast{}

	// Field: AnonymousField1 (Choice)
	{
		var choiceMatched bool
		if !choiceMatched {
			if pos < len(p.input) && p.input[pos] >= 'a' && p.input[pos] <= 'z' {
				result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
				pos++
				choiceMatched = true
			}
		}
		if !choiceMatched {
			if pos < len(p.input) && p.input[pos] >= 'A' && p.input[pos] <= 'Z' {
				result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
				pos++
				choiceMatched = true
			}
		}
		if !choiceMatched {
			if pos < len(p.input) && p.input[pos] >= '0' && p.input[pos] <= '9' {
				result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
				pos++
				choiceMatched = true
			}
		}
		if !choiceMatched {
			expected := []rune("_")
			if pos+len(expected) <= len(p.input) {
				ok := true
				for i, r := range expected {
					if p.input[pos+i] != r { ok = false; break }
				}
				if ok {
					result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
					pos += len(expected)
					choiceMatched = true
				}
			}
		}
		if !choiceMatched {
			err := fmt.Errorf("line %d: no choice matched for field AnonymousField1", p.lineAt(pos))
			p.memoize("SetayPathKeyLast", startPos, nil, pos, err)
			return nil, pos, err
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathKeyLast", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathQuotedKey(pos int) (*DefSetayPathQuotedKey, int, error) {
	if m, ok := p.getMemo("SetayPathQuotedKey", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathQuotedKey), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathQuotedKey{}

	// Field: AnonymousField1 (Choice)
	{
		var choiceMatched bool
		if !choiceMatched {
			node, end, err := p.parseSetayPathDqKey(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			node, end, err := p.parseSetayPathSqKey(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			err := fmt.Errorf("line %d: no choice matched for field AnonymousField1", p.lineAt(pos))
			p.memoize("SetayPathQuotedKey", startPos, nil, pos, err)
			return nil, pos, err
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathQuotedKey", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathDqKey(pos int) (*DefSetayPathDqKey, int, error) {
	if m, ok := p.getMemo("SetayPathDqKey", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathDqKey), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathDqKey{}

	// Field: AnonymousField1 (Literal "\"")
	{
		expected := []rune("\"")
		if pos+len(expected) > len(p.input) {
			err := fmt.Errorf("line %d: expected %q, got EOF", p.lineAt(pos), "\"")
			p.memoize("SetayPathDqKey", startPos, nil, pos, err)
			return nil, pos, err
		}
		matched := true
		for i, r := range expected {
			if p.input[pos+i] != r { matched = false; break }
		}
		if !matched {
			err := fmt.Errorf("line %d: expected %q", p.lineAt(pos), "\"")
			p.memoize("SetayPathDqKey", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
		pos += len(expected)
	}
	// Field: Content (Repeat with backtracking)
	{
		var repPositions []int
		repPositions = append(repPositions, pos) // initial position
		var repCount int
		for {
			repCount++
			if repCount > MaxRepeatCount { return nil, pos, ErrRepeatLimitExceeded }
			node, end, err := p.parseSetayPathDqContent(pos)
			if err != nil { break }
			result.Content = append(result.Content, node)
			pos = end
			repPositions = append(repPositions, pos)
		}
		for {
			var seqErr error
			seqPos := pos
			if seqErr == nil {
				expected := []rune("\"")
				ok := seqPos+len(expected) <= len(p.input)
				if ok {
					for i, r := range expected {
						if p.input[seqPos+i] != r { ok = false; break }
					}
				}
				if !ok {
					seqErr = fmt.Errorf("line %d: expected %q", p.lineAt(seqPos), "\"")
				} else {
					result.AnonymousField2 = p.makeStringFromSource(seqPos, seqPos+len(expected))
					seqPos += len(expected)
				}
			}
			if seqErr == nil {
				pos = seqPos
				break // success
			}
			if len(result.Content) == 0 {
				p.memoize("SetayPathDqKey", startPos, nil, pos, seqErr)
				return nil, pos, seqErr
			}
			result.Content = result.Content[:len(result.Content)-1]
			repPositions = repPositions[:len(repPositions)-1]
			pos = repPositions[len(repPositions)-1]
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathDqKey", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathDqContent(pos int) (*DefSetayPathDqContent, int, error) {
	if m, ok := p.getMemo("SetayPathDqContent", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathDqContent), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathDqContent{}

	// Field: AnonymousField1 (Choice)
	{
		var choiceMatched bool
		if !choiceMatched {
			node, end, err := p.parseSetayPathEscape(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			node, end, err := p.parseSetayPathDqNormal(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			err := fmt.Errorf("line %d: no choice matched for field AnonymousField1", p.lineAt(pos))
			p.memoize("SetayPathDqContent", startPos, nil, pos, err)
			return nil, pos, err
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathDqContent", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathDqNormal(pos int) (*DefSetayPathDqNormal, int, error) {
	if m, ok := p.getMemo("SetayPathDqNormal", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathDqNormal), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathDqNormal{}

	// Field: AnonymousField1 (AnycharExcept)
	{
		if pos >= len(p.input) {
			err := fmt.Errorf("line %d: expected any char, got EOF", p.lineAt(pos))
			p.memoize("SetayPathDqNormal", startPos, nil, pos, err)
			return nil, pos, err
		}
		ch := p.input[pos]
		excluded := false
		if ch == '"' { excluded = true }
		if ch == '\\' { excluded = true }
		if ch == '$' { excluded = true }
		if ch == '{' { excluded = true }
		if ch == '}' { excluded = true }
		if excluded {
			err := fmt.Errorf("line %d: char %q is in excluded set", p.lineAt(pos), string(ch))
			p.memoize("SetayPathDqNormal", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
		pos++
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathDqNormal", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathSqKey(pos int) (*DefSetayPathSqKey, int, error) {
	if m, ok := p.getMemo("SetayPathSqKey", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathSqKey), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathSqKey{}

	// Field: AnonymousField1 (Literal "'")
	{
		expected := []rune("'")
		if pos+len(expected) > len(p.input) {
			err := fmt.Errorf("line %d: expected %q, got EOF", p.lineAt(pos), "'")
			p.memoize("SetayPathSqKey", startPos, nil, pos, err)
			return nil, pos, err
		}
		matched := true
		for i, r := range expected {
			if p.input[pos+i] != r { matched = false; break }
		}
		if !matched {
			err := fmt.Errorf("line %d: expected %q", p.lineAt(pos), "'")
			p.memoize("SetayPathSqKey", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
		pos += len(expected)
	}
	// Field: Content (Repeat with backtracking)
	{
		var repPositions []int
		repPositions = append(repPositions, pos) // initial position
		var repCount int
		for {
			repCount++
			if repCount > MaxRepeatCount { return nil, pos, ErrRepeatLimitExceeded }
			node, end, err := p.parseSetayPathSqContent(pos)
			if err != nil { break }
			result.Content = append(result.Content, node)
			pos = end
			repPositions = append(repPositions, pos)
		}
		for {
			var seqErr error
			seqPos := pos
			if seqErr == nil {
				expected := []rune("'")
				ok := seqPos+len(expected) <= len(p.input)
				if ok {
					for i, r := range expected {
						if p.input[seqPos+i] != r { ok = false; break }
					}
				}
				if !ok {
					seqErr = fmt.Errorf("line %d: expected %q", p.lineAt(seqPos), "'")
				} else {
					result.AnonymousField2 = p.makeStringFromSource(seqPos, seqPos+len(expected))
					seqPos += len(expected)
				}
			}
			if seqErr == nil {
				pos = seqPos
				break // success
			}
			if len(result.Content) == 0 {
				p.memoize("SetayPathSqKey", startPos, nil, pos, seqErr)
				return nil, pos, seqErr
			}
			result.Content = result.Content[:len(result.Content)-1]
			repPositions = repPositions[:len(repPositions)-1]
			pos = repPositions[len(repPositions)-1]
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathSqKey", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathSqContent(pos int) (*DefSetayPathSqContent, int, error) {
	if m, ok := p.getMemo("SetayPathSqContent", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathSqContent), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathSqContent{}

	// Field: AnonymousField1 (Choice)
	{
		var choiceMatched bool
		if !choiceMatched {
			node, end, err := p.parseSetayPathEscape(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			node, end, err := p.parseSetayPathSqNormal(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			err := fmt.Errorf("line %d: no choice matched for field AnonymousField1", p.lineAt(pos))
			p.memoize("SetayPathSqContent", startPos, nil, pos, err)
			return nil, pos, err
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathSqContent", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathSqNormal(pos int) (*DefSetayPathSqNormal, int, error) {
	if m, ok := p.getMemo("SetayPathSqNormal", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathSqNormal), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathSqNormal{}

	// Field: AnonymousField1 (AnycharExcept)
	{
		if pos >= len(p.input) {
			err := fmt.Errorf("line %d: expected any char, got EOF", p.lineAt(pos))
			p.memoize("SetayPathSqNormal", startPos, nil, pos, err)
			return nil, pos, err
		}
		ch := p.input[pos]
		excluded := false
		if ch == '\'' { excluded = true }
		if ch == '\\' { excluded = true }
		if excluded {
			err := fmt.Errorf("line %d: char %q is in excluded set", p.lineAt(pos), string(ch))
			p.memoize("SetayPathSqNormal", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
		pos++
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathSqNormal", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathEscape(pos int) (*DefSetayPathEscape, int, error) {
	if m, ok := p.getMemo("SetayPathEscape", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathEscape), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathEscape{}

	// Field: AnonymousField1 (Literal "\\")
	{
		expected := []rune("\\")
		if pos+len(expected) > len(p.input) {
			err := fmt.Errorf("line %d: expected %q, got EOF", p.lineAt(pos), "\\")
			p.memoize("SetayPathEscape", startPos, nil, pos, err)
			return nil, pos, err
		}
		matched := true
		for i, r := range expected {
			if p.input[pos+i] != r { matched = false; break }
		}
		if !matched {
			err := fmt.Errorf("line %d: expected %q", p.lineAt(pos), "\\")
			p.memoize("SetayPathEscape", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
		pos += len(expected)
	}
	// Field: Ch (Reference -> SetayPathEscapeChar)
	{
		node, end, err := p.parseSetayPathEscapeChar(pos)
		if err != nil {
			p.memoize("SetayPathEscape", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.Ch = node
		pos = end
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathEscape", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathEscapeChar(pos int) (*DefSetayPathEscapeChar, int, error) {
	if m, ok := p.getMemo("SetayPathEscapeChar", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathEscapeChar), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathEscapeChar{}

	// Field: AnonymousField1 (Choice)
	{
		var choiceMatched bool
		if !choiceMatched {
			expected := []rune("n")
			if pos+len(expected) <= len(p.input) {
				ok := true
				for i, r := range expected {
					if p.input[pos+i] != r { ok = false; break }
				}
				if ok {
					result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
					pos += len(expected)
					choiceMatched = true
				}
			}
		}
		if !choiceMatched {
			expected := []rune("r")
			if pos+len(expected) <= len(p.input) {
				ok := true
				for i, r := range expected {
					if p.input[pos+i] != r { ok = false; break }
				}
				if ok {
					result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
					pos += len(expected)
					choiceMatched = true
				}
			}
		}
		if !choiceMatched {
			expected := []rune("t")
			if pos+len(expected) <= len(p.input) {
				ok := true
				for i, r := range expected {
					if p.input[pos+i] != r { ok = false; break }
				}
				if ok {
					result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
					pos += len(expected)
					choiceMatched = true
				}
			}
		}
		if !choiceMatched {
			expected := []rune("0")
			if pos+len(expected) <= len(p.input) {
				ok := true
				for i, r := range expected {
					if p.input[pos+i] != r { ok = false; break }
				}
				if ok {
					result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
					pos += len(expected)
					choiceMatched = true
				}
			}
		}
		if !choiceMatched {
			node, end, err := p.parseSetayPathHexEscape(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			node, end, err := p.parseSetayPathUnicode4(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			node, end, err := p.parseSetayPathUnicode8(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			node, end, err := p.parseSetayPathAsciiSymbol(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			err := fmt.Errorf("line %d: no choice matched for field AnonymousField1", p.lineAt(pos))
			p.memoize("SetayPathEscapeChar", startPos, nil, pos, err)
			return nil, pos, err
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathEscapeChar", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathAsciiSymbol(pos int) (*DefSetayPathAsciiSymbol, int, error) {
	if m, ok := p.getMemo("SetayPathAsciiSymbol", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathAsciiSymbol), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathAsciiSymbol{}

	// Field: AnonymousField1 (Choice)
	{
		var choiceMatched bool
		if !choiceMatched {
			if pos < len(p.input) && p.input[pos] >= '!' && p.input[pos] <= '/' {
				result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
				pos++
				choiceMatched = true
			}
		}
		if !choiceMatched {
			if pos < len(p.input) && p.input[pos] >= ':' && p.input[pos] <= '@' {
				result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
				pos++
				choiceMatched = true
			}
		}
		if !choiceMatched {
			if pos < len(p.input) && p.input[pos] >= '[' && p.input[pos] <= '`' {
				result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
				pos++
				choiceMatched = true
			}
		}
		if !choiceMatched {
			if pos < len(p.input) && p.input[pos] >= '{' && p.input[pos] <= '~' {
				result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
				pos++
				choiceMatched = true
			}
		}
		if !choiceMatched {
			err := fmt.Errorf("line %d: no choice matched for field AnonymousField1", p.lineAt(pos))
			p.memoize("SetayPathAsciiSymbol", startPos, nil, pos, err)
			return nil, pos, err
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathAsciiSymbol", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathHexEscape(pos int) (*DefSetayPathHexEscape, int, error) {
	if m, ok := p.getMemo("SetayPathHexEscape", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathHexEscape), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathHexEscape{}

	// Field: AnonymousField1 (Literal "x")
	{
		expected := []rune("x")
		if pos+len(expected) > len(p.input) {
			err := fmt.Errorf("line %d: expected %q, got EOF", p.lineAt(pos), "x")
			p.memoize("SetayPathHexEscape", startPos, nil, pos, err)
			return nil, pos, err
		}
		matched := true
		for i, r := range expected {
			if p.input[pos+i] != r { matched = false; break }
		}
		if !matched {
			err := fmt.Errorf("line %d: expected %q", p.lineAt(pos), "x")
			p.memoize("SetayPathHexEscape", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
		pos += len(expected)
	}
	// Field: AnonymousField2 (Reference -> SetayPathHex07)
	{
		node, end, err := p.parseSetayPathHex07(pos)
		if err != nil {
			p.memoize("SetayPathHexEscape", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField2 = node
		pos = end
	}
	// Field: AnonymousField3 (Reference -> SetayPathHexDigit)
	{
		node, end, err := p.parseSetayPathHexDigit(pos)
		if err != nil {
			p.memoize("SetayPathHexEscape", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField3 = node
		pos = end
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathHexEscape", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathHex07(pos int) (*DefSetayPathHex07, int, error) {
	if m, ok := p.getMemo("SetayPathHex07", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathHex07), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathHex07{}

	// Field: AnonymousField1 (CharRange)
	{
		if pos >= len(p.input) {
			err := fmt.Errorf("line %d: expected char in range '0'..'7', got EOF", p.lineAt(pos))
			p.memoize("SetayPathHex07", startPos, nil, pos, err)
			return nil, pos, err
		}
		ch := p.input[pos]
		if ch < '0' || ch > '7' {
			err := fmt.Errorf("line %d: char %q not in range '0'..'7'", p.lineAt(pos), string(ch))
			p.memoize("SetayPathHex07", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
		pos++
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathHex07", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathUnicode4(pos int) (*DefSetayPathUnicode4, int, error) {
	if m, ok := p.getMemo("SetayPathUnicode4", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathUnicode4), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathUnicode4{}

	// Field: AnonymousField1 (Literal "u")
	{
		expected := []rune("u")
		if pos+len(expected) > len(p.input) {
			err := fmt.Errorf("line %d: expected %q, got EOF", p.lineAt(pos), "u")
			p.memoize("SetayPathUnicode4", startPos, nil, pos, err)
			return nil, pos, err
		}
		matched := true
		for i, r := range expected {
			if p.input[pos+i] != r { matched = false; break }
		}
		if !matched {
			err := fmt.Errorf("line %d: expected %q", p.lineAt(pos), "u")
			p.memoize("SetayPathUnicode4", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
		pos += len(expected)
	}
	// Field: AnonymousField2 (Reference -> SetayPathHexDigit)
	{
		node, end, err := p.parseSetayPathHexDigit(pos)
		if err != nil {
			p.memoize("SetayPathUnicode4", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField2 = node
		pos = end
	}
	// Field: AnonymousField3 (Reference -> SetayPathHexDigit)
	{
		node, end, err := p.parseSetayPathHexDigit(pos)
		if err != nil {
			p.memoize("SetayPathUnicode4", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField3 = node
		pos = end
	}
	// Field: AnonymousField4 (Reference -> SetayPathHexDigit)
	{
		node, end, err := p.parseSetayPathHexDigit(pos)
		if err != nil {
			p.memoize("SetayPathUnicode4", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField4 = node
		pos = end
	}
	// Field: AnonymousField5 (Reference -> SetayPathHexDigit)
	{
		node, end, err := p.parseSetayPathHexDigit(pos)
		if err != nil {
			p.memoize("SetayPathUnicode4", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField5 = node
		pos = end
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathUnicode4", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathUnicode8(pos int) (*DefSetayPathUnicode8, int, error) {
	if m, ok := p.getMemo("SetayPathUnicode8", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathUnicode8), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathUnicode8{}

	// Field: AnonymousField1 (Literal "U")
	{
		expected := []rune("U")
		if pos+len(expected) > len(p.input) {
			err := fmt.Errorf("line %d: expected %q, got EOF", p.lineAt(pos), "U")
			p.memoize("SetayPathUnicode8", startPos, nil, pos, err)
			return nil, pos, err
		}
		matched := true
		for i, r := range expected {
			if p.input[pos+i] != r { matched = false; break }
		}
		if !matched {
			err := fmt.Errorf("line %d: expected %q", p.lineAt(pos), "U")
			p.memoize("SetayPathUnicode8", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
		pos += len(expected)
	}
	// Field: AnonymousField2 (Reference -> SetayPathHexDigit)
	{
		node, end, err := p.parseSetayPathHexDigit(pos)
		if err != nil {
			p.memoize("SetayPathUnicode8", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField2 = node
		pos = end
	}
	// Field: AnonymousField3 (Reference -> SetayPathHexDigit)
	{
		node, end, err := p.parseSetayPathHexDigit(pos)
		if err != nil {
			p.memoize("SetayPathUnicode8", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField3 = node
		pos = end
	}
	// Field: AnonymousField4 (Reference -> SetayPathHexDigit)
	{
		node, end, err := p.parseSetayPathHexDigit(pos)
		if err != nil {
			p.memoize("SetayPathUnicode8", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField4 = node
		pos = end
	}
	// Field: AnonymousField5 (Reference -> SetayPathHexDigit)
	{
		node, end, err := p.parseSetayPathHexDigit(pos)
		if err != nil {
			p.memoize("SetayPathUnicode8", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField5 = node
		pos = end
	}
	// Field: AnonymousField6 (Reference -> SetayPathHexDigit)
	{
		node, end, err := p.parseSetayPathHexDigit(pos)
		if err != nil {
			p.memoize("SetayPathUnicode8", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField6 = node
		pos = end
	}
	// Field: AnonymousField7 (Reference -> SetayPathHexDigit)
	{
		node, end, err := p.parseSetayPathHexDigit(pos)
		if err != nil {
			p.memoize("SetayPathUnicode8", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField7 = node
		pos = end
	}
	// Field: AnonymousField8 (Reference -> SetayPathHexDigit)
	{
		node, end, err := p.parseSetayPathHexDigit(pos)
		if err != nil {
			p.memoize("SetayPathUnicode8", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField8 = node
		pos = end
	}
	// Field: AnonymousField9 (Reference -> SetayPathHexDigit)
	{
		node, end, err := p.parseSetayPathHexDigit(pos)
		if err != nil {
			p.memoize("SetayPathUnicode8", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField9 = node
		pos = end
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathUnicode8", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathHexDigit(pos int) (*DefSetayPathHexDigit, int, error) {
	if m, ok := p.getMemo("SetayPathHexDigit", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathHexDigit), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathHexDigit{}

	// Field: AnonymousField1 (Choice)
	{
		var choiceMatched bool
		if !choiceMatched {
			if pos < len(p.input) && p.input[pos] >= '0' && p.input[pos] <= '9' {
				result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
				pos++
				choiceMatched = true
			}
		}
		if !choiceMatched {
			if pos < len(p.input) && p.input[pos] >= 'a' && p.input[pos] <= 'f' {
				result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
				pos++
				choiceMatched = true
			}
		}
		if !choiceMatched {
			if pos < len(p.input) && p.input[pos] >= 'A' && p.input[pos] <= 'F' {
				result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
				pos++
				choiceMatched = true
			}
		}
		if !choiceMatched {
			err := fmt.Errorf("line %d: no choice matched for field AnonymousField1", p.lineAt(pos))
			p.memoize("SetayPathHexDigit", startPos, nil, pos, err)
			return nil, pos, err
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathHexDigit", startPos, result, pos, nil)
	return result, pos, nil
}

