// Code generated by boompaw from path.bp. DO NOT EDIT.

package setaypath

import (
	"errors"
	"fmt"
	"strings"
)

var _ = fmt.Errorf
var _ = strings.HasPrefix


// Safety constants.
const (
	MaxParseDepth  = 2000
	MaxRepeatCount = 1_000_000
	MaxMemoEntries = 1_000_000
)

// Safety errors.
var (
	ErrDepthLimitExceeded  = errors.New("parse depth exceeded limit")
	ErrRepeatLimitExceeded = errors.New("repeat count exceeded limit")
	ErrMemoLimitExceeded   = errors.New("memo table exceeded limit")
)

// Position is a character position in source code (0-based, rune unit).
type Position int

// Length is the length of a node (rune unit).
type Length int

// LineNum is a line number in source code (1-based).
type LineNum int

// Authority holds the position information of a node in source code.
type Authority struct {
	SourceFilename string
	StartedAt      Position
	Length         Length
	StartedLineNum LineNum
	Surface        string
}

// ParseNode is the common interface for all parse result nodes.
type ParseNode interface {
	GetAuthority() *Authority
}

// StringFromSource holds a string and its position information from a leaf node.
type StringFromSource struct {
	Authority *Authority
	Surface   string
}

// GetAuthority implements ParseNode for StringFromSource.
func (s StringFromSource) GetAuthority() *Authority { return s.Authority }

type memoEntry struct {
	node ParseNode
	end  int
	err  error
}

// PackratParser is the packrat parser implementation.
type PackratParser struct {
	input       []rune
	memo        map[string]map[int]*memoEntry
	depth       int
	memoCount   int
	furthestPos int    // furthest position reached during parsing
	furthestMsg string // error message at the furthest position
	lineOffsets []int  // positions of each '\n' in input (pre-computed)
}

// NewPackratParser creates a new parser.
func NewPackratParser(input string) *PackratParser {
	runes := []rune(input)
	// Pre-compute line offset table: record position of every '\n'.
	var offsets []int
	for i, r := range runes {
		if r == '\n' {
			offsets = append(offsets, i)
		}
	}
	return &PackratParser{
		input:       runes,
		memo:        make(map[string]map[int]*memoEntry),
		furthestPos: -1,
		lineOffsets: offsets,
	}
}

func (p *PackratParser) enterRule() error {
	p.depth++
	if p.depth > MaxParseDepth {
		return fmt.Errorf("%w: depth=%d", ErrDepthLimitExceeded, p.depth)
	}
	return nil
}

func (p *PackratParser) leaveRule() {
	p.depth--
}

func (p *PackratParser) memoize(rule string, pos int, node ParseNode, end int, err error) {
	if p.memo[rule] == nil {
		p.memo[rule] = make(map[int]*memoEntry)
	}
	if _, exists := p.memo[rule][pos]; !exists {
		p.memoCount++
	}
	p.memo[rule][pos] = &memoEntry{node: node, end: end, err: err}
	if err != nil {
		p.trackFailure(end, err)
	}
}

func (p *PackratParser) trackFailure(pos int, err error) {
	if pos > p.furthestPos {
		p.furthestPos = pos
		p.furthestMsg = err.Error()
	}
}

func (p *PackratParser) getMemo(rule string, pos int) (*memoEntry, bool) {
	if m, ok := p.memo[rule]; ok {
		if e, ok := m[pos]; ok {
			return e, true
		}
	}
	return nil, false
}

func (p *PackratParser) lineAt(pos int) LineNum {
	// Binary search: find how many '\n' characters appear before pos.
	lo, hi := 0, len(p.lineOffsets)
	for lo < hi {
		mid := lo + (hi-lo)/2
		if p.lineOffsets[mid] < pos {
			lo = mid + 1
		} else {
			hi = mid
		}
	}
	return LineNum(lo + 1)
}

func (p *PackratParser) makeAuthority(start, end int) *Authority {
	return &Authority{
		StartedAt:      Position(start),
		Length:         Length(end - start),
		StartedLineNum: p.lineAt(start),
		Surface:        string(p.input[start:end]),
	}
}

func (p *PackratParser) makeStringFromSource(start, end int) StringFromSource {
	return StringFromSource{
		Authority: p.makeAuthority(start, end),
		Surface:   string(p.input[start:end]),
	}
}

func (p *PackratParser) extractIdentText(startPos, pos int) string {
	end := pos
	start := end
	for start > startPos {
		ch := p.input[start-1]
		if (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') ||
			(ch >= '0' && ch <= '9') || ch == '_' || ch == '-' {
			start--
		} else {
			break
		}
	}
	return string(p.input[start:end])
}

// DefSetayPath is the parse result of the SetayPath rule.
type DefSetayPath struct {
	Authority *Authority
	Steps []*DefSetayPathStep
}

func (n *DefSetayPath) GetAuthority() *Authority { return n.Authority }

// DefSetayPathStep is the parse result of the SetayPathStep rule.
type DefSetayPathStep struct {
	Authority *Authority
	AnonymousField1 ParseNode
}

func (n *DefSetayPathStep) GetAuthority() *Authority { return n.Authority }

// DefSetayPathDotField is the parse result of the SetayPathDotField rule.
type DefSetayPathDotField struct {
	Authority *Authority
	AnonymousField1 StringFromSource
	Name *DefSetayPathName
}

func (n *DefSetayPathDotField) GetAuthority() *Authority { return n.Authority }

// DefSetayPathName is the parse result of the SetayPathName rule.
type DefSetayPathName struct {
	Authority *Authority
	AnonymousField1 ParseNode
}

func (n *DefSetayPathName) GetAuthority() *Authority { return n.Authority }

// DefSetayPathBareName is the parse result of the SetayPathBareName rule.
type DefSetayPathBareName struct {
	Authority *Authority
	Lead *DefSetayPathNameLead
	Tail []*DefSetayPathNameCont
}

func (n *DefSetayPathBareName) GetAuthority() *Authority { return n.Authority }

// DefSetayPathNameLead is the parse result of the SetayPathNameLead rule.
type DefSetayPathNameLead struct {
	Authority *Authority
	AnonymousField1 ParseNode
}

func (n *DefSetayPathNameLead) GetAuthority() *Authority { return n.Authority }

// DefSetayPathNameCont is the parse result of the SetayPathNameCont rule.
type DefSetayPathNameCont struct {
	Authority *Authority
	AnonymousField1 ParseNode
}

func (n *DefSetayPathNameCont) GetAuthority() *Authority { return n.Authority }

// DefSetayPathQuoted is the parse result of the SetayPathQuoted rule.
type DefSetayPathQuoted struct {
	Authority *Authority
	AnonymousField1 StringFromSource
	Chars []*DefSetayPathQuotedChar
	AnonymousField2 StringFromSource
}

func (n *DefSetayPathQuoted) GetAuthority() *Authority { return n.Authority }

// DefSetayPathQuotedChar is the parse result of the SetayPathQuotedChar rule.
type DefSetayPathQuotedChar struct {
	Authority *Authority
	AnonymousField1 ParseNode
}

func (n *DefSetayPathQuotedChar) GetAuthority() *Authority { return n.Authority }

// DefSetayPathEscaped is the parse result of the SetayPathEscaped rule.
type DefSetayPathEscaped struct {
	Authority *Authority
	AnonymousField1 StringFromSource
	Ch StringFromSource
}

func (n *DefSetayPathEscaped) GetAuthority() *Authority { return n.Authority }

// DefSetayPathQuotedNormal is the parse result of the SetayPathQuotedNormal rule.
type DefSetayPathQuotedNormal struct {
	Authority *Authority
	AnonymousField1 StringFromSource
}

func (n *DefSetayPathQuotedNormal) GetAuthority() *Authority { return n.Authority }

// DefSetayPathDotBracket is the parse result of the SetayPathDotBracket rule.
type DefSetayPathDotBracket struct {
	Authority *Authority
	AnonymousField1 StringFromSource
	Bracket *DefSetayPathBracket
}

func (n *DefSetayPathDotBracket) GetAuthority() *Authority { return n.Authority }

// DefSetayPathBracket is the parse result of the SetayPathBracket rule.
type DefSetayPathBracket struct {
	Authority *Authority
	AnonymousField1 StringFromSource
	Inner *DefSetayPathBracketInner
	AnonymousField2 StringFromSource
}

func (n *DefSetayPathBracket) GetAuthority() *Authority { return n.Authority }

// DefSetayPathBracketInner is the parse result of the SetayPathBracketInner rule.
type DefSetayPathBracketInner struct {
	Authority *Authority
	AnonymousField1 ParseNode
}

func (n *DefSetayPathBracketInner) GetAuthority() *Authority { return n.Authority }

// DefSetayPathIndex is the parse result of the SetayPathIndex rule.
type DefSetayPathIndex struct {
	Authority *Authority
	Sign []*DefSetayPathMinus
	Digits []*DefSetayPathDigit
}

func (n *DefSetayPathIndex) GetAuthority() *Authority { return n.Authority }

// DefSetayPathMinus is the parse result of the SetayPathMinus rule.
type DefSetayPathMinus struct {
	Authority *Authority
	AnonymousField1 StringFromSource
}

func (n *DefSetayPathMinus) GetAuthority() *Authority { return n.Authority }

// DefSetayPathDigit is the parse result of the SetayPathDigit rule.
type DefSetayPathDigit struct {
	Authority *Authority
	AnonymousField1 StringFromSource
}

func (n *DefSetayPathDigit) GetAuthority() *Authority { return n.Authority }

// Parse parses the input string and returns a SetayPath.
func Parse(input string) (*DefSetayPath, error) {
	p := NewPackratParser(input)
	node, end, err := p.parseSetayPath(0)
	if err != nil {
		if p.furthestPos > 0 {
			return nil, fmt.Errorf("Parse error at position %d (line %d): %s — near: %q", p.furthestPos, p.lineAt(p.furthestPos), p.furthestMsg, string(p.input[p.furthestPos:min(p.furthestPos+20, len(p.input))]))
		}
		return nil, err
	}
	if end < len(p.input) {
		if p.furthestPos > end {
			return nil, fmt.Errorf("Parse error at position %d (line %d): %s — near: %q", p.furthestPos, p.lineAt(p.furthestPos), p.furthestMsg, string(p.input[p.furthestPos:min(p.furthestPos+20, len(p.input))]))
		}
		return nil, fmt.Errorf("unexpected input at position %d (line %d): %q", end, p.lineAt(end), string(p.input[end:min(end+20, len(p.input))]))
	}
	return node, nil
}

func (p *PackratParser) parseSetayPath(pos int) (*DefSetayPath, int, error) {
	if m, ok := p.getMemo("SetayPath", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPath), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPath{}

	// Field: Steps (Repeat)
	{
		var repCount int
		for {
			repCount++
			if repCount > MaxRepeatCount { return nil, pos, ErrRepeatLimitExceeded }
			node, end, err := p.parseSetayPathStep(pos)
			if err != nil { break }
			if end == pos { break } // prevent zero-length match
			result.Steps = append(result.Steps, node)
			pos = end
		}
		if len(result.Steps) < 1 {
			err := fmt.Errorf("line %d: expected at least 1 items for Steps", p.lineAt(pos))
			p.memoize("SetayPath", startPos, nil, pos, err)
			return nil, pos, err
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPath", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathStep(pos int) (*DefSetayPathStep, int, error) {
	if m, ok := p.getMemo("SetayPathStep", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathStep), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathStep{}

	// Field: AnonymousField1 (Choice)
	{
		var choiceMatched bool
		if !choiceMatched {
			node, end, err := p.parseSetayPathDotField(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			node, end, err := p.parseSetayPathDotBracket(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			node, end, err := p.parseSetayPathBracket(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			err := fmt.Errorf("line %d: no choice matched for field AnonymousField1", p.lineAt(pos))
			p.memoize("SetayPathStep", startPos, nil, pos, err)
			return nil, pos, err
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathStep", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathDotField(pos int) (*DefSetayPathDotField, int, error) {
	if m, ok := p.getMemo("SetayPathDotField", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathDotField), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathDotField{}

	// Field: AnonymousField1 (Literal ".")
	{
		expected := []rune(".")
		if pos+len(expected) > len(p.input) {
			err := fmt.Errorf("line %d: expected %q, got EOF", p.lineAt(pos), ".")
			p.memoize("SetayPathDotField", startPos, nil, pos, err)
			return nil, pos, err
		}
		matched := true
		for i, r := range expected {
			if p.input[pos+i] != r { matched = false; break }
		}
		if !matched {
			err := fmt.Errorf("line %d: expected %q", p.lineAt(pos), ".")
			p.memoize("SetayPathDotField", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
		pos += len(expected)
	}
	// Field: Name (Reference -> SetayPathName)
	{
		node, end, err := p.parseSetayPathName(pos)
		if err != nil {
			p.memoize("SetayPathDotField", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.Name = node
		pos = end
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathDotField", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathName(pos int) (*DefSetayPathName, int, error) {
	if m, ok := p.getMemo("SetayPathName", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathName), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathName{}

	// Field: AnonymousField1 (Choice)
	{
		var choiceMatched bool
		if !choiceMatched {
			node, end, err := p.parseSetayPathBareName(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			node, end, err := p.parseSetayPathQuoted(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			err := fmt.Errorf("line %d: no choice matched for field AnonymousField1", p.lineAt(pos))
			p.memoize("SetayPathName", startPos, nil, pos, err)
			return nil, pos, err
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathName", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathBareName(pos int) (*DefSetayPathBareName, int, error) {
	if m, ok := p.getMemo("SetayPathBareName", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathBareName), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathBareName{}

	// Field: Lead (Reference -> SetayPathNameLead)
	{
		node, end, err := p.parseSetayPathNameLead(pos)
		if err != nil {
			p.memoize("SetayPathBareName", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.Lead = node
		pos = end
	}
	// Field: Tail (Repeat)
	{
		var repCount int
		for {
			repCount++
			if repCount > MaxRepeatCount { return nil, pos, ErrRepeatLimitExceeded }
			node, end, err := p.parseSetayPathNameCont(pos)
			if err != nil { break }
			if end == pos { break } // prevent zero-length match
			result.Tail = append(result.Tail, node)
			pos = end
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathBareName", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathNameLead(pos int) (*DefSetayPathNameLead, int, error) {
	if m, ok := p.getMemo("SetayPathNameLead", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathNameLead), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathNameLead{}

	// Field: AnonymousField1 (Choice)
	{
		var choiceMatched bool
		if !choiceMatched {
			if pos < len(p.input) && p.input[pos] >= 'a' && p.input[pos] <= 'z' {
				result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
				pos++
				choiceMatched = true
			}
		}
		if !choiceMatched {
			if pos < len(p.input) && p.input[pos] >= 'A' && p.input[pos] <= 'Z' {
				result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
				pos++
				choiceMatched = true
			}
		}
		if !choiceMatched {
			expected := []rune("_")
			if pos+len(expected) <= len(p.input) {
				ok := true
				for i, r := range expected {
					if p.input[pos+i] != r { ok = false; break }
				}
				if ok {
					result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
					pos += len(expected)
					choiceMatched = true
				}
			}
		}
		if !choiceMatched {
			err := fmt.Errorf("line %d: no choice matched for field AnonymousField1", p.lineAt(pos))
			p.memoize("SetayPathNameLead", startPos, nil, pos, err)
			return nil, pos, err
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathNameLead", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathNameCont(pos int) (*DefSetayPathNameCont, int, error) {
	if m, ok := p.getMemo("SetayPathNameCont", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathNameCont), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathNameCont{}

	// Field: AnonymousField1 (Choice)
	{
		var choiceMatched bool
		if !choiceMatched {
			if pos < len(p.input) && p.input[pos] >= 'a' && p.input[pos] <= 'z' {
				result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
				pos++
				choiceMatched = true
			}
		}
		if !choiceMatched {
			if pos < len(p.input) && p.input[pos] >= 'A' && p.input[pos] <= 'Z' {
				result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
				pos++
				choiceMatched = true
			}
		}
		if !choiceMatched {
			if pos < len(p.input) && p.input[pos] >= '0' && p.input[pos] <= '9' {
				result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
				pos++
				choiceMatched = true
			}
		}
		if !choiceMatched {
			expected := []rune("_")
			if pos+len(expected) <= len(p.input) {
				ok := true
				for i, r := range expected {
					if p.input[pos+i] != r { ok = false; break }
				}
				if ok {
					result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
					pos += len(expected)
					choiceMatched = true
				}
			}
		}
		if !choiceMatched {
			expected := []rune("-")
			if pos+len(expected) <= len(p.input) {
				ok := true
				for i, r := range expected {
					if p.input[pos+i] != r { ok = false; break }
				}
				if ok {
					result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
					pos += len(expected)
					choiceMatched = true
				}
			}
		}
		if !choiceMatched {
			err := fmt.Errorf("line %d: no choice matched for field AnonymousField1", p.lineAt(pos))
			p.memoize("SetayPathNameCont", startPos, nil, pos, err)
			return nil, pos, err
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathNameCont", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathQuoted(pos int) (*DefSetayPathQuoted, int, error) {
	if m, ok := p.getMemo("SetayPathQuoted", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathQuoted), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathQuoted{}

	// Field: AnonymousField1 (Literal "\"")
	{
		expected := []rune("\"")
		if pos+len(expected) > len(p.input) {
			err := fmt.Errorf("line %d: expected %q, got EOF", p.lineAt(pos), "\"")
			p.memoize("SetayPathQuoted", startPos, nil, pos, err)
			return nil, pos, err
		}
		matched := true
		for i, r := range expected {
			if p.input[pos+i] != r { matched = false; break }
		}
		if !matched {
			err := fmt.Errorf("line %d: expected %q", p.lineAt(pos), "\"")
			p.memoize("SetayPathQuoted", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
		pos += len(expected)
	}
	// Field: Chars (Repeat with backtracking)
	{
		var repPositions []int
		repPositions = append(repPositions, pos) // initial position
		var repCount int
		for {
			repCount++
			if repCount > MaxRepeatCount { return nil, pos, ErrRepeatLimitExceeded }
			node, end, err := p.parseSetayPathQuotedChar(pos)
			if err != nil { break }
			result.Chars = append(result.Chars, node)
			pos = end
			repPositions = append(repPositions, pos)
		}
		for {
			var seqErr error
			seqPos := pos
			if seqErr == nil {
				expected := []rune("\"")
				ok := seqPos+len(expected) <= len(p.input)
				if ok {
					for i, r := range expected {
						if p.input[seqPos+i] != r { ok = false; break }
					}
				}
				if !ok {
					seqErr = fmt.Errorf("line %d: expected %q", p.lineAt(seqPos), "\"")
				} else {
					result.AnonymousField2 = p.makeStringFromSource(seqPos, seqPos+len(expected))
					seqPos += len(expected)
				}
			}
			if seqErr == nil {
				pos = seqPos
				break // success
			}
			if len(result.Chars) == 0 {
				p.memoize("SetayPathQuoted", startPos, nil, pos, seqErr)
				return nil, pos, seqErr
			}
			result.Chars = result.Chars[:len(result.Chars)-1]
			repPositions = repPositions[:len(repPositions)-1]
			pos = repPositions[len(repPositions)-1]
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathQuoted", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathQuotedChar(pos int) (*DefSetayPathQuotedChar, int, error) {
	if m, ok := p.getMemo("SetayPathQuotedChar", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathQuotedChar), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathQuotedChar{}

	// Field: AnonymousField1 (Choice)
	{
		var choiceMatched bool
		if !choiceMatched {
			node, end, err := p.parseSetayPathEscaped(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			node, end, err := p.parseSetayPathQuotedNormal(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			err := fmt.Errorf("line %d: no choice matched for field AnonymousField1", p.lineAt(pos))
			p.memoize("SetayPathQuotedChar", startPos, nil, pos, err)
			return nil, pos, err
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathQuotedChar", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathEscaped(pos int) (*DefSetayPathEscaped, int, error) {
	if m, ok := p.getMemo("SetayPathEscaped", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathEscaped), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathEscaped{}

	// Field: AnonymousField1 (Literal "\\")
	{
		expected := []rune("\\")
		if pos+len(expected) > len(p.input) {
			err := fmt.Errorf("line %d: expected %q, got EOF", p.lineAt(pos), "\\")
			p.memoize("SetayPathEscaped", startPos, nil, pos, err)
			return nil, pos, err
		}
		matched := true
		for i, r := range expected {
			if p.input[pos+i] != r { matched = false; break }
		}
		if !matched {
			err := fmt.Errorf("line %d: expected %q", p.lineAt(pos), "\\")
			p.memoize("SetayPathEscaped", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
		pos += len(expected)
	}
	// Field: Ch (Anychar)
	{
		if pos >= len(p.input) {
			err := fmt.Errorf("line %d: expected any char, got EOF", p.lineAt(pos))
			p.memoize("SetayPathEscaped", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.Ch = p.makeStringFromSource(pos, pos+1)
		pos++
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathEscaped", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathQuotedNormal(pos int) (*DefSetayPathQuotedNormal, int, error) {
	if m, ok := p.getMemo("SetayPathQuotedNormal", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathQuotedNormal), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathQuotedNormal{}

	// Field: AnonymousField1 (AnycharExcept)
	{
		if pos >= len(p.input) {
			err := fmt.Errorf("line %d: expected any char, got EOF", p.lineAt(pos))
			p.memoize("SetayPathQuotedNormal", startPos, nil, pos, err)
			return nil, pos, err
		}
		ch := p.input[pos]
		excluded := false
		if ch == '"' { excluded = true }
		if ch == '\\' { excluded = true }
		if excluded {
			err := fmt.Errorf("line %d: char %q is in excluded set", p.lineAt(pos), string(ch))
			p.memoize("SetayPathQuotedNormal", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
		pos++
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathQuotedNormal", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathDotBracket(pos int) (*DefSetayPathDotBracket, int, error) {
	if m, ok := p.getMemo("SetayPathDotBracket", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathDotBracket), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathDotBracket{}

	// Field: AnonymousField1 (Literal ".")
	{
		expected := []rune(".")
		if pos+len(expected) > len(p.input) {
			err := fmt.Errorf("line %d: expected %q, got EOF", p.lineAt(pos), ".")
			p.memoize("SetayPathDotBracket", startPos, nil, pos, err)
			return nil, pos, err
		}
		matched := true
		for i, r := range expected {
			if p.input[pos+i] != r { matched = false; break }
		}
		if !matched {
			err := fmt.Errorf("line %d: expected %q", p.lineAt(pos), ".")
			p.memoize("SetayPathDotBracket", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
		pos += len(expected)
	}
	// Field: Bracket (Reference -> SetayPathBracket)
	{
		node, end, err := p.parseSetayPathBracket(pos)
		if err != nil {
			p.memoize("SetayPathDotBracket", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.Bracket = node
		pos = end
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathDotBracket", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathBracket(pos int) (*DefSetayPathBracket, int, error) {
	if m, ok := p.getMemo("SetayPathBracket", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathBracket), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathBracket{}

	// Field: AnonymousField1 (Literal "[")
	{
		expected := []rune("[")
		if pos+len(expected) > len(p.input) {
			err := fmt.Errorf("line %d: expected %q, got EOF", p.lineAt(pos), "[")
			p.memoize("SetayPathBracket", startPos, nil, pos, err)
			return nil, pos, err
		}
		matched := true
		for i, r := range expected {
			if p.input[pos+i] != r { matched = false; break }
		}
		if !matched {
			err := fmt.Errorf("line %d: expected %q", p.lineAt(pos), "[")
			p.memoize("SetayPathBracket", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
		pos += len(expected)
	}
	// Field: Inner (Reference -> SetayPathBracketInner)
	{
		node, end, err := p.parseSetayPathBracketInner(pos)
		if err != nil {
			p.memoize("SetayPathBracket", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.Inner = node
		pos = end
	}
	// Field: AnonymousField2 (Literal "]")
	{
		expected := []rune("]")
		if pos+len(expected) > len(p.input) {
			err := fmt.Errorf("line %d: expected %q, got EOF", p.lineAt(pos), "]")
			p.memoize("SetayPathBracket", startPos, nil, pos, err)
			return nil, pos, err
		}
		matched := true
		for i, r := range expected {
			if p.input[pos+i] != r { matched = false; break }
		}
		if !matched {
			err := fmt.Errorf("line %d: expected %q", p.lineAt(pos), "]")
			p.memoize("SetayPathBracket", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField2 = p.makeStringFromSource(pos, pos+len(expected))
		pos += len(expected)
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathBracket", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathBracketInner(pos int) (*DefSetayPathBracketInner, int, error) {
	if m, ok := p.getMemo("SetayPathBracketInner", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathBracketInner), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathBracketInner{}

	// Field: AnonymousField1 (Choice)
	{
		var choiceMatched bool
		if !choiceMatched {
			node, end, err := p.parseSetayPathIndex(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			node, end, err := p.parseSetayPathQuoted(pos)
			if err == nil {
				result.AnonymousField1 = node
				pos = end
				choiceMatched = true
			}
		}
		if !choiceMatched {
			err := fmt.Errorf("line %d: no choice matched for field AnonymousField1", p.lineAt(pos))
			p.memoize("SetayPathBracketInner", startPos, nil, pos, err)
			return nil, pos, err
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathBracketInner", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathIndex(pos int) (*DefSetayPathIndex, int, error) {
	if m, ok := p.getMemo("SetayPathIndex", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathIndex), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathIndex{}

	// Field: Sign (Repeat with backtracking)
	{
		var repPositions []int
		repPositions = append(repPositions, pos) // initial position
		var repCount int
		for {
			repCount++
			if repCount > MaxRepeatCount { return nil, pos, ErrRepeatLimitExceeded }
			node, end, err := p.parseSetayPathMinus(pos)
			if err != nil { break }
			result.Sign = append(result.Sign, node)
			pos = end
			repPositions = append(repPositions, pos)
			if len(result.Sign) >= 1 { break }
		}
		for {
			var seqErr error
			seqPos := pos
			if seqErr == nil {
				var repCount int
				for {
					repCount++
					if repCount > MaxRepeatCount { seqErr = ErrRepeatLimitExceeded; break }
					node, end, err := p.parseSetayPathDigit(seqPos)
					if err != nil { break }
					result.Digits = append(result.Digits, node)
					seqPos = end
				}
				if seqErr == nil && len(result.Digits) < 1 {
					seqErr = fmt.Errorf("line %d: expected at least 1 items for Digits", p.lineAt(seqPos))
				}
			}
			if seqErr == nil {
				pos = seqPos
				break // success
			}
			if len(result.Sign) == 0 {
				p.memoize("SetayPathIndex", startPos, nil, pos, seqErr)
				return nil, pos, seqErr
			}
			result.Sign = result.Sign[:len(result.Sign)-1]
			repPositions = repPositions[:len(repPositions)-1]
			pos = repPositions[len(repPositions)-1]
		}
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathIndex", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathMinus(pos int) (*DefSetayPathMinus, int, error) {
	if m, ok := p.getMemo("SetayPathMinus", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathMinus), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathMinus{}

	// Field: AnonymousField1 (Literal "-")
	{
		expected := []rune("-")
		if pos+len(expected) > len(p.input) {
			err := fmt.Errorf("line %d: expected %q, got EOF", p.lineAt(pos), "-")
			p.memoize("SetayPathMinus", startPos, nil, pos, err)
			return nil, pos, err
		}
		matched := true
		for i, r := range expected {
			if p.input[pos+i] != r { matched = false; break }
		}
		if !matched {
			err := fmt.Errorf("line %d: expected %q", p.lineAt(pos), "-")
			p.memoize("SetayPathMinus", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+len(expected))
		pos += len(expected)
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathMinus", startPos, result, pos, nil)
	return result, pos, nil
}

func (p *PackratParser) parseSetayPathDigit(pos int) (*DefSetayPathDigit, int, error) {
	if m, ok := p.getMemo("SetayPathDigit", pos); ok {
		if m.err != nil {
			return nil, m.end, m.err
		}
		return m.node.(*DefSetayPathDigit), m.end, nil
	}

	if err := p.enterRule(); err != nil {
		return nil, pos, err
	}
	defer p.leaveRule()

	startPos := pos
	result := &DefSetayPathDigit{}

	// Field: AnonymousField1 (CharRange)
	{
		if pos >= len(p.input) {
			err := fmt.Errorf("line %d: expected char in range '0'..'9', got EOF", p.lineAt(pos))
			p.memoize("SetayPathDigit", startPos, nil, pos, err)
			return nil, pos, err
		}
		ch := p.input[pos]
		if ch < '0' || ch > '9' {
			err := fmt.Errorf("line %d: char %q not in range '0'..'9'", p.lineAt(pos), string(ch))
			p.memoize("SetayPathDigit", startPos, nil, pos, err)
			return nil, pos, err
		}
		result.AnonymousField1 = p.makeStringFromSource(pos, pos+1)
		pos++
	}
	result.Authority = p.makeAuthority(startPos, pos)
	p.memoize("SetayPathDigit", startPos, result, pos, nil)
	return result, pos, nil
}

